# Generated by Django 5.1.7 on 2025-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_tanggal_lahir_farmproduct_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmproduct',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmproduct',
            name='price',
        ),
    ]
